// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// SolarUIClient is the client API for SolarUI service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SolarUIClient interface {
	// ListPanelSpecs returns a list of Panel(s) that can be started through the UI.
	ListPanelSpecs(ctx context.Context, in *ListPanelSpecsRequest, opts ...grpc.CallOption) (SolarUI_ListPanelSpecsClient, error)
	// IsReadOnly returns true if the UI is readonly.
	IsReadOnly(ctx context.Context, in *IsReadOnlyRequest, opts ...grpc.CallOption) (*IsReadOnlyResponse, error)
}

type solarUIClient struct {
	cc grpc.ClientConnInterface
}

func NewSolarUIClient(cc grpc.ClientConnInterface) SolarUIClient {
	return &solarUIClient{cc}
}

func (c *solarUIClient) ListPanelSpecs(ctx context.Context, in *ListPanelSpecsRequest, opts ...grpc.CallOption) (SolarUI_ListPanelSpecsClient, error) {
	stream, err := c.cc.NewStream(ctx, &SolarUI_ServiceDesc.Streams[0], "/v1.SolarUI/ListPanelSpecs", opts...)
	if err != nil {
		return nil, err
	}
	x := &solarUIListPanelSpecsClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type SolarUI_ListPanelSpecsClient interface {
	Recv() (*ListPanelSpecsResponse, error)
	grpc.ClientStream
}

type solarUIListPanelSpecsClient struct {
	grpc.ClientStream
}

func (x *solarUIListPanelSpecsClient) Recv() (*ListPanelSpecsResponse, error) {
	m := new(ListPanelSpecsResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *solarUIClient) IsReadOnly(ctx context.Context, in *IsReadOnlyRequest, opts ...grpc.CallOption) (*IsReadOnlyResponse, error) {
	out := new(IsReadOnlyResponse)
	err := c.cc.Invoke(ctx, "/v1.SolarUI/IsReadOnly", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SolarUIServer is the server API for SolarUI service.
// All implementations must embed UnimplementedSolarUIServer
// for forward compatibility
type SolarUIServer interface {
	// ListPanelSpecs returns a list of Panel(s) that can be started through the UI.
	ListPanelSpecs(*ListPanelSpecsRequest, SolarUI_ListPanelSpecsServer) error
	// IsReadOnly returns true if the UI is readonly.
	IsReadOnly(context.Context, *IsReadOnlyRequest) (*IsReadOnlyResponse, error)
	mustEmbedUnimplementedSolarUIServer()
}

// UnimplementedSolarUIServer must be embedded to have forward compatible implementations.
type UnimplementedSolarUIServer struct {
}

func (UnimplementedSolarUIServer) ListPanelSpecs(*ListPanelSpecsRequest, SolarUI_ListPanelSpecsServer) error {
	return status.Errorf(codes.Unimplemented, "method ListPanelSpecs not implemented")
}
func (UnimplementedSolarUIServer) IsReadOnly(context.Context, *IsReadOnlyRequest) (*IsReadOnlyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method IsReadOnly not implemented")
}
func (UnimplementedSolarUIServer) mustEmbedUnimplementedSolarUIServer() {}

// UnsafeSolarUIServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SolarUIServer will
// result in compilation errors.
type UnsafeSolarUIServer interface {
	mustEmbedUnimplementedSolarUIServer()
}

func RegisterSolarUIServer(s grpc.ServiceRegistrar, srv SolarUIServer) {
	s.RegisterService(&SolarUI_ServiceDesc, srv)
}

func _SolarUI_ListPanelSpecs_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ListPanelSpecsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(SolarUIServer).ListPanelSpecs(m, &solarUIListPanelSpecsServer{stream})
}

type SolarUI_ListPanelSpecsServer interface {
	Send(*ListPanelSpecsResponse) error
	grpc.ServerStream
}

type solarUIListPanelSpecsServer struct {
	grpc.ServerStream
}

func (x *solarUIListPanelSpecsServer) Send(m *ListPanelSpecsResponse) error {
	return x.ServerStream.SendMsg(m)
}

func _SolarUI_IsReadOnly_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IsReadOnlyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SolarUIServer).IsReadOnly(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/v1.SolarUI/IsReadOnly",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SolarUIServer).IsReadOnly(ctx, req.(*IsReadOnlyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SolarUI_ServiceDesc is the grpc.ServiceDesc for SolarUI service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SolarUI_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "v1.SolarUI",
	HandlerType: (*SolarUIServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "IsReadOnly",
			Handler:    _SolarUI_IsReadOnly_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ListPanelSpecs",
			Handler:       _SolarUI_ListPanelSpecs_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "solar-ui.proto",
}
